consumer_key: <%= ENV['FUNNER_TWITTER_CONSUMER_KEY'] %>
consumer_secret: <%= ENV['FUNNER_TWITTER_CONSUMER_SECRET'] %>
access_token: <%= ENV['FUNNER_TWITTER_TOKEN'] %>
access_token_secret: <%= ENV['FUNNER_TWITTER_TOKEN_SECRET'] %>
